# Test generated by RoostGPT for test credential-wallet-rest-assured using AI Type Azure Open AI and AI Model roost-gpt4-32k


# RoostTestHash=aa0a5d4980

config:
  target: "{{ $processEnvironment.API_HOST }}"
  plugins:
    expect: {}
  payload:
    path: "persons_get_others.csv"
    fields:
      - "username"
      - "password"
    skipHeader: true
  phases:
    - duration: 60
      arrivalRate: 5
  environments:
    common:
      - target: "http://api.example.com"

scenarios:
  - name: "Non-success API requests test"
    flow:
      - post: 
          url: "/recipients/persons" 
          json: 
            username: "{{ username }}"
            password: "{{ password }}"
          headers: 
            Token: "{{$processEnvironment.AUTH_TOKEN}}"
          expect: 
            - statusCode: 401
            - hasProperty: "error"
            - hasProperty: "description"
            - headerEquals: 
                api-version: "1.0.0"
          # We expect a 401 - Unauthorized access to verify incorrect authentication flow
      - think: 1
      - post: 
          url: "/recipients/persons"
          json: 
            username: "{{ username }}"
            password: "wrongpassword"
          headers: 
            Token: "{{$processEnvironment.AUTH_TOKEN}}"
          expect: 
            - statusCode: 400
            - hasProperty: "error"
            - hasProperty: "description"
            - headerEquals: 
                api-version: "1.0.0"
          # We expect a 400 - Bad Request to verify incorrect password handling
      - think: 1
      - get: 
          url: "/invalid/url"
          headers: 
            Token: "{{$processEnvironment.AUTH_TOKEN}}"
          expect: 
            - statusCode: 404
          # We expect a 404 â€“ Not Found error for incorrect endpoints
